branchName: '${issue.number}-${issue.title,}'

branches:
  - label: feature
    prefix: feature/
  - label: enhacement
    prefix: enhacement/
  - label: performance
    prefix: performance/
  - label: fix
    prefix: fix/
  - label: bug
    prefix: bug/
  - label: patch
    prefix: patch/
  - label: docs
    prefix: docs/
  - label: research
    skip: true
