name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'performance'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'patch'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'docs'

# change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'stable'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhacement'
      - 'performance'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
  default: patch

autolabeler:
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'enhacement'
    branch:
      - '/enhacement\/.+/'
  - label: 'performance'
    branch:
      - '/performance\/.+/'
  - label: 'docs'
    branch:
      - '/docs\/.+/'
  - label: 'patch'
    branch:
      - '/patch\/.+/'
  - label: 'bug'
    branch:
      - '/bug\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'

template: |
  ## Changes

  $CHANGES
