---
name: CI Pipeline with Deployment using Semantic Versioning

#
# ┌──────┐   ┌───────┐   ┌────────┐   ┌──────────┐
# │ Test │   │ Build │   │Push to │   │Update K8s│
# │      ├──►│ Image ├──►│Registry├──►│manifests │
# └──────┘   └───────┘   └────────┘   └──────────┘
# 

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE_NAME: test_image
  REGISTRY_URL: registry.idener.es
  DEPLOY_ENABLE: true
  DEPLOY_REPO: idener/CD-Test

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

# test:

  build-and-push:
    name: Build & push image
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Get image tag from reference context
        run: echo ${{ github.ref }} | sed -e 's/refs\/tags\//TAG=/' >> $GITHUB_ENV

      - name: Kaniko builder
        uses: aevea/action-kaniko@v0.9.0
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ env.TAG }}
          tag_with_latest: true
          strip_tag_prefix: v

  update-tags:
    name: Update image tags
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Get image tag from reference context
        run: echo ${{ github.ref }} | sed -e 's/refs\/tags\/v/TAG=/' >> $GITHUB_ENV

      - name: Update image tag in the deployment repository
        uses: idener/kustomize-tag-updater-action@main
        if: env.DEPLOY_ENABLE == 'true'
        with:
          repo: ${{ env.DEPLOY_REPO }}
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ env.TAG }}
          ssh-key: "${{ secrets.REPO_SSH }}"


#=============================================================================#
#
# NOTE: If you're having trouble login with container registry, use this code 
# snippet instead of the Kaniko action:
#
#    - name: Get image tag from reference context
#      run: echo ${{ github.ref }} | sed -e 's/refs\/tags\/v/TAG=/' >> $GITHUB_ENV
#
#    - name: Create config file with registry credentials
#      run: |
#        echo '{"auths":{"https://${{ env.REGISTRY_URL }}":{"username":"${{ secrets.REGISTRY_USERNAME }}","password":"${{ secrets.REGISTRY_PASSWORD }}"}}}' > $HOME/config.json
#
#    - name: Build the image with Kaniko and push to registry
#      run: |
#        docker run \
#          -v $(pwd):/$GITHUB_WORKSPACE \
#          -v $HOME/config.json:/kaniko/.docker/config.json:ro \
#          gcr.io/kaniko-project/executor:latest \
#          --destination "${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}" \
#          --destination "${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest" \
#          --dockerfile $GITHUB_WORKSPACE/Dockerfile \
#          --context $GITHUB_WORKSPACE
#
#=============================================================================#
